#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)
# Usage: ./0-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_infor () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_infor "$1" "www"
  domain_infor "$1" "lb-01"
  domain_infor "$1" "web-01"
  domain_infor "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_infor "$1" "$2"
fi


