#!/usr/bin/env bash
# Install Nginx

sudo apt-get update
sudo apt-get install nginx -y

# create a hello world page
echo "Hello World!" | sudo tee /var/www/html/index.html

# create a redirection for our website
sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n	}' /etc/nginx/sites-available/default


# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                internal;\n        }' /etc/nginx/sites-available/default
sudo service nginx start
