#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

sudo apt-get update
sudo apt-get -y install nginx

# Create a default web page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Set up 301 redirection for /redirect_me
ADD301_REDIRECT="
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
"

# Add the 301 redirection to the end of the default Nginx configuration
sudo bash -c "echo '$ADD301_REDIRECT' >> /etc/nginx/sites-available/default"

# Restart Nginx to apply the changes
sudo service nginx restart
