#!/usr/bin/env bash
# only shows listening sockets(Active Internet connections)
# shows the PID and name of the program to which each socket belongs
# sudo netstat -natp can be used 

sudo netstat -lp
