#!/usr/bin/env bash
# a Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntua Bash script that uses# ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu

sh -i ~/.ssh/school ubuntu@54.87.178.144
